return {
	"nvim-treesitter/nvim-treesitter",
	branch = "master", -- master is locked, main branch is major rewrite
	pin = true,
	lazy = false,
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter").install({
			"bash",
			"c",
			"diff",
			"elm",
			"html",
			"haskell",
			"javascript",
			"jsdoc",
			"json",
			"jsonc",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"printf",
			"scheme",
			"clojure",
			"commonlisp",
			"hare",
			"odin",
			"nim",
			"python",
			"query",
			"regex",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
		})
	end,
}
